apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
    - name: debian-container
      image: debian
      command: ["/bin/sh", "-c"]
      args: ["while true; do date >> /html/index.html; sleep 1; done"]
      volumeMounts:
        - mountPath: /html
          name: html
  volumes:
    - name: html
      emptyDir: {}
      